### ISSUE TITLE
Be able to compare simulations in the Comparator by selecting forcings or RIP values

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#10]
WHO: Gavin Schmidt

First the API must be able index forcings (ticket #5).
Second the comparator must be able to compare simulation documents (ticket #9).

Eric and Karl will provide input on what the selection workflow might look like.

**Comment by murphysj** [comment]
Considered top priority at the Feb 2015 F2F meeting.

**Comment by bnlawrence** [comment]
This is part of the further_info_url use case ... we'll likely close this as a duplicate once we have a full set of further_info_url issues loaded up.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#19
