### ISSUE TITLE
Collect metrics for IS-ENES

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#103]
WHO: Sebastien

The is-enes2 project want to identify how much esdoc is being used. To that end we will need measure of request coming to esdoc api. 

We also want to discriminate the source of the call (from ESGF, from climate4impact, from the isenes portal and ....(add your favorite).

**Comment by murphysj** [comment]
I have been trying to collect this information too: Here is my current summary
https://www.earthsystemcog.org/projects/es-doc-models/who_is_using_esdoc_tools

We want to know who has linked to es-doc tools, which is a primary user, and not just who lands on the tools via those thinks, which might be considered a downstream user.

**Comment by eguil** [comment]
Implemented
