### ISSUE TITLE
Change display of License "Is Restricted?"

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#104]
WHO: ESPS

Several ESPS documents have the "Is Restricted ?" checkbox enabled w/o out any other license information, so by itself, the attribute means nothing. 

Instead, change the display to either a) have a license subcategory bar (like we do for citations) that says License or b) add the work license to the attribute display name.

**Comment by momipsl** [comment]
Please give an example

**Comment by murphysj** [comment]
see screen shot of the current display of this instance: 
![coamps](https://cloud.githubusercontent.com/assets/1512704/12181822/c20f1e1e-b541-11e5-985d-6dd9f3e842e8.png)

Here is the document in the feed:
http://questionnaire.es-doc.org/feed/esps/cim_1.10.0/modelcomponent/8cec115c-7440-4834-b84f-df9b62550ee3/10/

**Comment by murphysj** [comment]
On a side note, there is a space between Unrestricted and the question mark. 

Luca does the same thing and we are always have to change the code. Is that a European way of doing things? In the U.S. there is no space.

**Comment by allynt** [comment]
This is not an issue w/ the Viewer.  The user has not given the license a name in the Q.  Without that information, I'm not sure what you else you expect to be displayed?
