### ISSUE TITLE
When and how to upgrade experiment descriptions?

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-docs#106]
Charlotte is building experimental descriptions for CMIP6 with an early variant of CIM2. When and how can we upgrade them?

**Comment by momipsl** [comment]
There is also the option of simply modifying the [spreadsheet --> cim docs writer](https://github.com/ES-DOC/esdoc-py-client/blob/master/jobs/run_cmip6_write_experiments.py).

**Comment by charliepascoe** [comment]
I was talking to David Hassle about this very thing on Tuesday.
It'd be *relatively* straightforward for me to update the spreadsheets but it would be useful to know whether I should be working with a tagged version of the CIM or the leading edge.

**Comment by allynt** [comment]
This is related to #136.

**Comment by momipsl** [comment]
The spreadsheet processing script is the agent truly responsible for mapping the spreadsheet data to CIM documents.  This is already correctly mapping to latest CIM v2.
