### ISSUE TITLE
Link Resolution when documents are created "out of order"

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-docs#107]
We expect documents to have links between them, and be produced at different times.

Eg. `Doc A` `->` `Doc B` and that is handled using a `DocumentReference` type, but what do we put in Document A if Document B doesn't exist, or if it exists, but is not complete (and published) when Document A is published? 

This can be handled in the "publication repository" by updating document A when document B exists, but is this automagic?

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-py-client#9
