### ISSUE TITLE
Reset of CMIP5 simulation documents - action needed.

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-docs#108]
The output of CMIP5 includes 600 simulations in CIM1.5, the obvious thing to do is to evolve these to CIM2 ... which means we now know that we will need a CMIP5 and a CMIP6 specialisation of Simulation.` There is a [ticket](https://bitbucket.org/bnlawrence/esdoc-nb/issues/255/) for this on CIM2 ( from an information model perspective, the action here is to execute and update the content.

**Comment by murphysj** [comment]
@bnlawrence 
does this need to be done for the first CMIP6 test (end of June) or is this something that can be done much later?

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-cdf2cim#3
