### ISSUE TITLE
CMIP5 to CIM2/CMIP6 model description for ocean

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#109]
The institutes have put alot of work into entering information using the CMIP5-Q.  The CMIP6 descriptions need to be reused as much as possible.

This will involve creating mappings between CMIP5 and CMIP6 'vocabs'.

**Comment by eguil** [comment]
Requires realms coordinators to create matching tables for each realm:
CMIP6 id -> CMIP5 id

**Comment by murphysj** [comment]
Does this ticket refer to CIM2 "specifications" or pyesdoc, or the questionnaire. Can we be more specific?

**Comment by eguil** [comment]
Milestone "Convert CMIP5 docs to CIM2/CMIP6" created - this becomes an ocean specific ticket for testing the tooling and procedure

**Comment by eguil** [comment]
First version done and added to the ocean-specialisation repo

**Comment by allynt** [comment]
This issue was moved to ES-DOC/cmip6-specializations-ocean#8
