### ISSUE TITLE
Be able to view offline CIM documents held locally on disk 

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#11]
WHO: Dev Team

Sometimes groups want to look at intermediate CIM documents in the Viewer before uploading to the CIM Archive.

**Comment by murphysj** [comment]
There are several groups that are using pyesdoc to create CIM documents. They have a need to view these documents before publishing.

**Comment by murphysj** [comment]
Considered top priority at the Feb 2015 F2F meeting.

**Comment by davidhassell** [comment]
Can do by encoding as HTML and viewing in browser.
