### ISSUE TITLE
Institutes require vocabs as configuration inputs to their internal metadata systems

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#110]
'Vocabs' will need to be available in encodings such as JSON in order to act as inputs into an institute's internal metadata systems.

**Comment by davidhassell** [comment]
I presume that this is to be dealt with by pyesdoc converting from a python dictionary source ...

**Comment by allynt** [comment]
This is related to #121

**Comment by momipsl** [comment]
A dedicated script was developed to perform this.
