### ISSUE TITLE
Define the complete workflow around the creation and usage of further_info_url

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-docs#111]
We expect the target of a further_info_url to be an "ensemble_page" (the semantic content of this page is  [ticketed in CIM2](https://bitbucket.org/bnlawrence/esdoc-nb/issues/257)), but we need to ensure a blank is created during ESGF publication by the es-doc hook, and that editing tools are available for modellign groups.

**Comment by allynt** [comment]
This is related to #117 & #135; @davidhassell to potentially merge.

**Comment by davidhassell** [comment]
I think that this can be covered by #135 (create) and #117 (edit)
