### ISSUE TITLE
Create Root Model (e.g. coupled system) CMIP6 specialization

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#115]
CMIP6 model python vocab CIM2 specialisation, to include:
1) Model (top level): model properties, tuning, flux correction, CMIP genealogy, others (see IPCC table)
2) a suitably flexible constraint syntax in the .py files (incl. documentation and templates)

**Comment by eguil** [comment]
need to add following labels: CMIP6, VOCABS (I cannot do it it seems)

**Comment by davidhassell** [comment]
Also include
3) a suitably flexible constraint syntax in the `.py` files

**Comment by eguil** [comment]
First go at model 
![screen shot 2016-03-11 at 16 42 16](https://cloud.githubusercontent.com/assets/7075402/13707104/5ad76dde-e7a8-11e5-9f5c-c25776c420f1.jpg)
top level mindmap

**Comment by murphysj** [comment]
Tickets have now been opened for each realm so we can track the separately.

**Comment by allynt** [comment]
This issue was moved to ES-DOC/cmip6-specializations-toplevel#3
