### ISSUE TITLE
Need to think through the plan for editing further_info_url

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-docs#117]
It's straight forward to create a template, but what if a group want to over-write it, how do they know what UUID to use? Need a tool (DRS based) to grab the appropriate target? Or is this easy via the further_info_url.

**Comment by davidhassell** [comment]
Is this the right place to discuss the content of the template. E.g. I presume that it will be automatically populated with Simulation documents  (which themselves have been autogenerated during the dataset publication process)?

**Comment by eguil** [comment]
David, is this the same ticket as #135 ? If so please merge them

**Comment by davidhassell** [comment]
I think you're right that my comment belongs in #135, but this ticket should still remain, perhaps with a tweaked title. I've changed it to: "Need to think through the plan for ensemble template editting"

**Comment by MartinaSt** [comment]
It was agreed within the WIP that the Data Citation Information are integrated into the page, furtherInfoURL is pointing to. We need to discuss the interface. The data citation provides information in JSON format. 

Syntax: http://cera-www.dkrz.de/WDCC/CMIP6/CitationJSON.jsp?name=<DRS_id of model or ensemble>
CMIP5 test data example:
http://cera-www.dkrz.de/WDCC/CMIP6/CitationJSON.jsp?name=cmip5.output1.MPI-M.MPI-ESM-P.lgm

**Comment by davidhassell** [comment]
Hi Martina,

Is the case the Data Citation Information should be rendered? By that I mean, when you click on "Data Citation Information" from the furtherInfoURL page, would you want to see the raw JSON and/or a nice, more human consumable form?

Is the "http://cera-www.dkrz.de/WDCC/CMIP6/CitationJSON.jsp" part of the URL set in stone? If so then when we (=ES-DOC) create the furtherInfoURL web page, the citation link can be automatically created, I think.

**Comment by MartinaSt** [comment]
Hi David,

rendering of the basic citation information would be preference: Authors, PublicationYear, Title, PID/DOI (clickable with underlying URL). The user-friendly version of the citation information is accessible via the landing page URL "http://cera-www.dkrz.de/WDCC/CMIP6/Citation.jsp" (analogously constructed as CitationJSON.jsp).

This URL template will be used for CMIP6. We will replace the underlying developing database schema (and content) by the operational, when we will have real content.

**Comment by davidhassell** [comment]
Ok - no problem, I imagine.

One question (which exposes my incomplete understanding of the data publication process) - will citations for _all_ datasets be available at "http://cera-www.dkrz.de/", regardless from which node they were published?

**Comment by MartinaSt** [comment]
Yes, David, the citation information will be centrally collected and displayed (same as CIM). The landing page will include a link to the data in the ESGF and therefore indirectly link to the node, where the data is located / was published.

**Comment by davidhassell** [comment]
Martina - Great, this all sounds fine to me. Mark and I are meeting next week to discuss some of the technicalities of surrounding this sort of functionality. David

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-project#7
