### ISSUE TITLE
Dealing with grids in the questionnaire

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-docs#118]
A typical model will have fewer grids than realms. A grid document may be shared between realms. E.g. Atmosphere and Aerosol will often link to the same grid document; Ocean and Ocean BGC could  both link to a *different* grid document.

Furthermore, there may be grid specialisations defined in the some of the CMIP6 realms. The other realms may either link to these defined grids _or use their own non-specialised grids_.

The questionnaire will need to deal with this, somehow.

**Comment by davidhassell** [comment]
My initial thoughts on this are ...

When creating a grid document in the Q, I envisage a choice being offered between creating a i) "standard" (non-specialised) grid and ii) one of the defined specialised grids.

Then, when setting the grid for a realm, all you need to do is choose one of the existing grid documents, providing you can identify them by model and grid type.

Does that sound at all feasible, Allyn?

**Comment by allynt** [comment]
This makes sense to me.

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-questionnaire#471
