### ISSUE TITLE
Define the syntax for specifying vocabularies

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-docs#119]
Finalise the python dictionary syntax for defining CIM2 specializations. See below for a work-in-progress example.

Still to do:
  * Work out a fully flexible constraint syntax (so that we can constrain more than just value and have multiple constrains on one property)
  * Provide templates for the different document types (model, realm, process, grid)

  * Provide basic, in-line documentation on the (currently) 8 types of entity in the file (`ID`, `CIM`, `TYPE`, `CONTACT`, `AUTHORS`, `DATE`, `PROPERTIES`, `ENUMERATIONS`)
  * other things

**Example**:
```
ID = 'cmip6.ocean.grid'

CIM = '2.0'

TYPE = 'science.grid'

CONTACT = 'Eric Guilyardi (e-mail)'

AUTHORS = 'Eric Guilyardi (e-mail), David Hassell (e-mail)'

DATE = '2016-03-10'

PROPERTIES = {
    # ----------------------------------------------------------------
    # OVERVIEW
    # ----------------------------------------------------------------
    'short_name': 'Ocean grid',
    'description': 'Overview of ocean grid'
   
    'discretisation': ['ocean_discretisatsion'],

    'details': ['vertical_grid',
                'horizontal_grid'],

    # ----------------------------------------------------------------
    # DETAILS
    # ----------------------------------------------------------------
    'vertical_grid': {
        'description': 'Properties of vertical coordinate in ocean',
        'short_name': 'Properties of vertical coordinate in ocean',
        'number_of_vertical_levels', (
            'int', '1.1',
            'Number of vertical levs'),
    },

    'horizontal_grid': {
        'description': 'Properties of H coordinate in ocean',
        'short_name': 'Properties of H coordinate in ocean',
        'is_adaptive': (
            'bool', '0.1',
            'Default is False. Set true if grid resolution changes during execution.'),
        'number_of_horizontal_gridpoints': (
            'int', '0.1',
            'Total number of horizontal points on computational grid'),
    },

    # ----------------------------------------------------------------
    # DISCRETISATION
    # ----------------------------------------------------------------
    'ocean_discretisation': {
        'short_name': 'Type of discretisation scheme in ocean',
        'description': 'Type of discretisation scheme in ocean',
        'details': {
            'vertical_discretisation': {
                'description': 'Properties of vertical coordinate in ocean',
                'short_name': 'Properties of vertical coordinate in ocean',
                'coord_type', (
                    'ENUM:vertical_coord_types', '1.1',
                    'Types of vertical coordinates in ocean',),
                'partial_steps': (
                    'bool', '1.1',
                    'Using partial steps with Z or Z* vertical coordinate in ocean ?'),
            },
            'horizontal_discretisation': {
                'short_name': 'Type of horizontal discretisation scheme in ocean',
                'description': 'Type of horizontal discretisation scheme in ocean',
                'scheme': (
                    'ENUM:horiz_scheme_types', '1.1',
                    'Types of horizonal schemes in ocean',),
                'ocean_pole_singularity_treatment': (
                    'str', '1.1',
                    'Describe how the North Pole singularity is treated (filter, pole rotation/displacement, artificial island, ...)'),
            },
        },                
    },
},

# ====================================================================
# ENUMERATED LISTS
# ====================================================================

ENUMS = {
    'horiz_scheme_types': {
        'description': 'Types of horizonal schemes in ocean',
        'members': [
            ('Finite difference / Arakawa B-grid','tbd'),
            ('Finite difference / Arakawa C-grid','tbd'),
            ('Finite difference / Arakawa E-grid','tbd'),
            ('Finite volumes', 'tbd'),
            ('Finite elements', 'tbd'),
            ('Other', 'tbd')
        ],
    },
    
    'vertical_coord_types': {
        'description': 'Types of vertical coordinates in ocean',
        'members': [
            ('Z-coordinate','tbd'),
            ('Z*-coordinate', 'tbd'),
            ('S-coordinate', 'tbd'),
            ('Isopycnic - sigma 0','Density referenced to the surface'),
            ('Isopycnic - sigma 2','Density referenced to 2000 m'),
            ('Isopycnic - sigma 4','Density referenced to 4000 m'),
            ('Isopycnic - other','Other density-based coordinate'),
            ('Hybrid / Z+S', 'tbd'),
            ('Hybrid / Z+isopycnic', 'tbd'),
            ('Hybrid / ALE', 'tbd'),
            ('Hybrid / other', 'tbd'),
            ('Pressure referenced (P)', 'tbd'),
            ('P*','tbd'),
            ('Z**', 'tbd'),
            ('Other', 'tbd')
        ],
    },
}
```

**Comment by davidhassell** [comment]
Should also have some sort of `VERSION = 1.0` in the file. I reckon that this can this be lightweight and independent of other vocab files, etc. Just so different versions same file may be easily differentiated.

**Comment by davidhassell** [comment]
@momipsl, could you sketch out the directory structure you have in mind for the CMIP6 specilaization files, so that I can put it into my development branch? Will it look something like `cmip6/model.py`, `cmip6/ocean/key_properties.py`? Where will `ocean.py` (the file for the scientific realm rather than its scientific processes) go? in `cmip6/` or `cmip6/ocean/`? Thanks, David

**Comment by davidhassell** [comment]
I have transliterated into the current version of the new syntax Charlotte's comprehensive CMIP5-as-a-starting-point-for-CMIP6 atmosphere specialisation: Files `atmosphere_*.py` in https://bitbucket.org/davidhassell/esdoc-nb/src/master/esdoc_nb/mp/core/schema/cmip6

**Comment by davidhassell** [comment]
Generalised constraint ideas:

* Constrain a value:
`'short_name': 'Atmosphere Radiation',`
or, equivalently in a 2-tuple:
`'short_name': ('CONSTRAINT:value', 'Atmosphere Radiation'),`

* Constrain something other than value:
`'short_name': ('CONSTRAINT:cardinality', '0.0'),`

* Constrain multiple things:
`'short_name': ('CONSTRAINT:cardinality', '1.1', 'CONSTRAINT:value', 'Atmosphere Radiation'),```

**Comment by davidhassell** [comment]
Last time I'll mention this (I promise), but just to highlight that when a detail group contains just one property there could be a lot of duplication of information when creating a specialisation. The alternative is to allow properties to added directly to specialisations of `process` and `sub_process`, but I do appreciate the benefits of _not_ allowing this (i.e. te staus quo).

Here's an example from sea ice:
```
'dynamics': { ## A science.sub_process
     'details': {  ## A science.detail with just 1 property
            'horizontal_advection': {
                'short_name': 'Horizontal Advection of Sea Ice',
                'description': 'Method of horizontal advection',
                'method': (
                    'ENUM:transport_methods', '0.1',
                    'Method of horizontal advection'),
            },
},
```
The alternative view would be:
```
'dynamics': { ## A science.sub_process
     'method': (
         'ENUM:transport_methods', '0.1',
         'Method of horizontal advection'),
},
```
Just had a thought - perhaps the parser could create a `science.detail` containing just the one property (cf. the first bit of code) from the latter, shorter, less redundant code that the vocab writers would rather(?) produce. That way we could i) avoid the difficulties of allowing properties to be set directly on classes higher up the tree and ii) make it easier to create specializations.

**Comment by davidhassell** [comment]
Revised idea: Stick with a `science.detail`, but allow `short_name` and `description` to be optional in the _syntax_ (not the CIM) when there's just one property:
```
'dynamics': { ## A science.sub_process
     'details': {  ## A science.detail with just 1 property
            'horizontal_advection': {
                'method': (
                    'ENUM:transport_methods', '0.1',
                    'Method of horizontal advection'),
            },
},
```
The parser would create something like `'short_name': 'horizontal advection',` and `'description': Method of horizontal advection',`

**Comment by davidhassell** [comment]
First stab at syntax rules:

https://bitbucket.org/davidhassell/esdoc-nb/src/master/esdoc_nb/mp/core/schema/cmip6/syntax_specification.txt

These are a bit dry and out of context, so I've in-lined these rules with descriptions in an example:

 https://bitbucket.org/davidhassell/esdoc-nb/src/master/esdoc_nb/mp/core/schema/cmip6/atmosphere_cloud_scheme.py

Still missing are rules on generalised constraints. I'll do these when I've had some feedback on my proposal (on this ticket). There are no examples yet in ocean/atmosphere/seaice which utilise this extended syntax, so I left it for now.

A proper, stand alone document will eventually be created, of course and will no doubt be arranged quite differently!

**Comment by bnlawrence** [comment]
I've had a go at parsing these, but there are some discrepancies of approach between you and Eric.
For example, the lines [147](https://bitbucket.org/davidhassell/esdoc-nb/src/master/esdoc_nb/mp/core/schema/cmip6/atmosphere_cloud_scheme.py?fileviewer=file-view-default#atmosphere_cloud_scheme.py-147)-[166](https://bitbucket.org/davidhassell/esdoc-nb/src/master/esdoc_nb/mp/core/schema/cmip6/atmosphere_cloud_scheme.py?fileviewer=file-view-default#atmosphere_cloud_scheme.py-166) define a detail *inline* under sub-process, but Eric defines such details by naming them, and then defining them in the details section (e.g. [54](https://bitbucket.org/bnlawrence/esdoc-nb/src/8bf3483308aeae6a6278cb7b171545f7d02a8c19/esdoc_nb/mp/core/schema/cmip6/ocean_vertical_physics.py?at=master&fileviewer=file-view-default#ocean_vertical_physics.py-54)-[58](https://bitbucket.org/bnlawrence/esdoc-nb/src/8bf3483308aeae6a6278cb7b171545f7d02a8c19/esdoc_nb/mp/core/schema/cmip6/ocean_vertical_physics.py?at=master&fileviewer=file-view-default#ocean_vertical_physics.py-58)).

**Comment by davidhassell** [comment]
Should we drop the `ENUM:` prefix to enumeration names? It's purely an issue of signposting and readability. It is of no consequence to the tools.

**Comment by bnlawrence** [comment]
(I'd be happy for you to drop ENUM, it adds complexity to the parsing for no value, since we know the only things that aren't python str/float/int that go here are enums.)

**Comment by davidhassell** [comment]
I've just read https://github.com/ES-DOC/esdoc-cim/wiki/Constraints, and suspect that my suggested constraint syntax could fall short. I'll have a re-think. Suggestions welcome ...

**Comment by bnlawrence** [comment]
(Um, why, remember that that documentation is for the full schema constraint specification, are you saying you can't recreate all the options? Or that it would be ambiguous?

**Comment by davidhassell** [comment]
Um, good point. Probably that I can't recreate all options. On reflection, the only one that might be an issue is `constraints':[('process','constant', ['cmip6.clouds','cmip6.radiation'])]`. Is something that a specialisation will want to specialise?

As an aside, how do you find, aesthetically, the proposed syntax, above? I've just had an alternative (but similar) idea, which I'll put together in another comment.

**Comment by davidhassell** [comment]
Here's an attempt at not in-lining details, and at the same time providing important property order information which was hitherto missing. As Bryan points out, it will make error finding easier and I think that it makes the file cleaner for humans. The gist is that a reference to a `science.details` is followed by the properties that it contains, in the order in which you would like them to be used.
```
PROPERTIES = {
#<snip>

    # ----------------------------------------------------------------
    # SUB-PROCESSES
    # ----------------------------------------------------------------
    'large_scale_precipitation': {
        'short_name': 'Large scale precipitation scheme',
        'descr_detailsiption': 'Large scale precipitation scheme',
        'details': [('large_scale_precipitation_details',
                     'scheme', 'hydrometeors'),
                ],
    },    

    'cloud_microphysics': { 
        'short_name': 'Cloud microphysics',
        'description': 'Cloud microphysics',
        'details': [('cloud_microphysics_details',
                    'scheme', 'processes'),
                ],               
    },

    # ----------------------------------------------------------------
    # SUB-PROCESS DETAILS
    # ----------------------------------------------------------------
    'large_scale_precipitation_details': {
        'short_name': 'Large scale precipitation scheme properties',
        'description': 'Large scale precipitation scheme properties',
        'scheme': (
            'str', '1.1',
            'Commonly used name of the large scale precipitation parameterisation scheme'),
        'hydrometeors': (
            'ENUM:large_scale_precipitation_hydrometeor_types', '1.N',
            'Precipitating hydrometeors taken into account in the large scale precipitation scheme'),
    },
    
    'cloud_microphysics_details': { 
        'short_name': 'Cloud microphysics properties',
        'description': 'Cloud microphysics properties',
        'scheme': (
            'str', '1.1',
            'Commonly used name of the microphysics parameterisation scheme.'),
        'processes': (
            'ENUM:cloud_microphysics_processes_attributes', '1.N',
            'Cloud microphysics processes'),
    },
}
```
Full files: https://bitbucket.org/davidhassell/esdoc-nb/src/master/esdoc_nb/mp/core/schema/specializations/cmip6

**Comment by momipsl** [comment]
Property order is implicit in the sequence of definitions and hence does not need to be specified twice.  Also inlining details in my view makes it easier to read & actually less error prone.  But at this point I am a little confused as to the state of play.

**Comment by davidhassell** [comment]
Ah - I suppose it's a question of how you parse the file. If you read it as python dictionaries then the key order is surely lost. Can you the parser read them as ordered dictionaries?

**Comment by momipsl** [comment]
Yes good point about dictionary sort order.  Defining properties as a collection of 4 member tuples (name, type, cardinailty, doc-string) would get around this.

**Comment by davidhassell** [comment]
E.g.?
```
'large_scale_precipitation_details': {
        'short_name': 'Large scale precipitation scheme properties',
        'description': 'Large scale precipitation scheme properties',
        'properties': [
            ('scheme', 'str', '1.1',
             'Commonly used name of the large scale precipitation parameterisation scheme'),
            ('hydrometeors', 'large_scale_precipitation_hydrometeor_types', '1.N',
             'Precipitating hydrometeors taken into account in the large scale precipitation scheme'),
        ],
    },```

**Comment by momipsl** [comment]
Yes.  Then is it necessary to include both short_name & description ?

**Comment by davidhassell** [comment]
Good point. I think they should be optional. they are defined in as `1.1` in a `science.details`, but if they are omitted in the syntax then they could be inferred by the parser. In the above example, 'large_scale_precipitation_details' are details of the 'large_scale_precipitation' sub-process, so the details' short_name could be something like `'Details of '+PROPERTIES['large_scale_precipitation']['short_name']`, or similar, and likewise for description.

Many details groups have just one property, and short_name/description is definitely a pain to provide. For larger groups, it may be nice to add bespoke detail.

**Comment by bnlawrence** [comment]
The short/name description is there to provide the (optional) ability to give context to a detailed question (and the answer). You probably want to see how these look in a mock up (e.g. the notebook) to decide how much you need this ...

**Comment by davidhassell** [comment]
Do mean "optional" in the specialisation, or in the CIM. They're `1.1` in latter, and I think that that's right.

**Comment by bnlawrence** [comment]
Hmm. Yes, we'll they're both 1.1, and maybe they don't both need to be. Arguably as you say, the name can be inferred (but I think a proper string would be better), and sometimes the description is just fluff.  We can suck it and see ...

**Comment by davidhassell** [comment]
Sounds good. This is only for science.details, and the typical use case is for when there is only one property, so fluff is probably ok most of the time. Perhaps the short_name/description should only be optional when there is just one property?

**Comment by murphysj** [comment]
Where are we with this ticket. Has the specialization syntax been finalized or is it going to have to be realm by realm?

**Comment by davidhassell** [comment]
Done.
