### ISSUE TITLE
CMIP6 CV tooling for modelling groups

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#121]
Develop, document and provide ES-DOC tools needed by group to create CIM documents for CMIP6

**Comment by murphysj** [comment]
@eguil 
Note sure what you mean by this ticket. The title says CV, the descriptions says create CIM documents. They are two different things.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-py-client#6
