### ISSUE TITLE
CIM2 viewer support

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#125]
CIM2 viewer support (<22/6)

**Comment by murphysj** [comment]
@eguil 
do we mean document a user's guide? If so this is a duplicate. 

do we mean some sort of support structure to answer questions? If so that is already in place.

**Comment by eguil** [comment]
@momipsl - We need Mark to review this ticket

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#2
