### ISSUE TITLE
Display unique CESM attributes in the Viewer 

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#13]
WHO: CESM

CESM auto generates CIM XML from model runs. They have added more properties to the CIM and export these in their XML. 

Enable the Viewer to display these properties.

Find out if these properties are included in a specific version of the CIM...e.g. 1.8. It is possible this is already done.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#16
