### ISSUE TITLE
ES-DOC white paper for WIP

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#132]
High level white paper describing ES-DOC for CMIP6 (for 22/6)
See January 2016 DRAFT attached:
[DRAFT_Formal Documention for CMIP6.pdf](https://github.com/ES-DOC/esdoc-docs/files/168732/DRAFT_Formal.Documention.for.CMIP6.pdf)

**Comment by allynt** [comment]
[es-doc_f2f_minutes.pdf](https://github.com/ES-DOC/esdoc-docs/files/210652/es-doc_f2f_minutes.pdf)

**Comment by eguil** [comment]
First draft sent to WIP - see https://docs.google.com/document/d/1vsqeEDutNcZN4pHK534MAnkF5sKXcmjPAEfADdJNeF0/edit
