### ISSUE TITLE
Create and review Model Component documents workflow diagram

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#134]
Create workflow diagram for Model Component document creation including QC:
- Add UID and versioning in workflows
- Fit in CIM documents
- Review (ME)

Where to put version on github ?

**Comment by eguil** [comment]
Current version (from March 2016 F2F meeting)
![screen shot 2016-03-15 at 17 16 38](https://cloud.githubusercontent.com/assets/7075402/13784962/b75367bc-ead1-11e5-99a9-e5b922b14af8.jpg)

**Comment by davidhassell** [comment]
Latest model documentation flow chart
![model_v2](https://cloud.githubusercontent.com/assets/8126576/16015174/6b3097ea-318c-11e6-9e39-f2f48f32a246.png)
