### ISSUE TITLE
Create and review a Simulation and Ensembles documents workflow diagram

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#135]
Simulation and ensembles workflow:
- include further_url
- conformance to exp. requirements
- ESGF link
  +
- Add UID and versioning in workflows
- Fit in CIM documents
- Review (ME)

**Comment by davidhassell** [comment]
Just noting that "Fit in CIM documents" means "Automatically including inserting links to Simulation documents into the ensemble template page"

**Comment by davidhassell** [comment]
Zero-th draft of Simulation workflow
[Simulation_workflow_v0.pdf](https://github.com/ES-DOC/esdoc-docs/files/176221/Simulation_workflow_v0.pdf)

**Comment by davidhassell** [comment]
Version 1 - after consultation with Ag Stephens. Also includes a little bit more detail on further_info_URL. [Simulation_workflow_v1.pdf](https://github.com/ES-DOC/esdoc-docs/files/202815/Simulation_workflow_v1.pdf)

**Comment by eguil** [comment]
see discussion on slack channel cmip6-workflows

**Comment by davidhassell** [comment]
Latest.
[Simulation_workflow_v7.pdf](https://github.com/ES-DOC/esdoc-docs/files/313408/Simulation_workflow_v7.pdf)

**Comment by eguil** [comment]
forcings documentation could be based on 
1) single base description document 
2) simulation specific changes to address protocol requirements (CMIP5 Q - like)

**Comment by davidhassell** [comment]
![simulation_workflow_v8_page1](https://cloud.githubusercontent.com/assets/8126576/16409543/0e052d20-3d16-11e6-937c-105d1463e9f6.png)
![simulation_workflow_v8_page2](https://cloud.githubusercontent.com/assets/8126576/16409547/14fa1b9a-3d16-11e6-80bb-86ceb7384b23.png)
