### ISSUE TITLE
Move ES-DOC web "home" to wordpress

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#139]
What are the steps here:

1) Create the initial site
2) Move over the current information
3) Add pages for documentation from other tickets in this milestone
4) Move the url
5) Archive the old site ... remove from the stack?

**Comment by murphysj** [comment]
@momipsl 

please update the steps in the initial description with what you think is necessary to go this fully.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#1

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-web#32
