### ISSUE TITLE
Bring CMIP6 specializations from bitbucket to github

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#141]
Currently the most recent version of the CMIP6 specialisations reside in a @davidhassell bitbucket repo.  When can they be moved to the esdoc-cim repo ?

**Comment by momipsl** [comment]
I guess there are no software artefacts of note that are dependent upon them at this point in time and thus we can move the specialisations across immediately.

**Comment by eguil** [comment]
ok - does that mean that I now have to work from github for the ocean ?

**Comment by momipsl** [comment]
Coordinate with @davidhassell on when to move the ocean definitions to GitHub.  However we were of the view that it would be a good idea to create a dedicated repo per realm, e.g. cmip6-specializations-ocean.  The realm specialization authors would then push to the realm specific repo and either David or I would then merge the realm definitions into the master within the esdoc-cim repo.  This way people will be less likely to tread on each others feet so to speak.

**Comment by eguil** [comment]
ok sounds good. I can add directly to github as I have not yet put ocean files on bitbucket. @davidhassell, what do you think ?
