### ISSUE TITLE
Create a mindmap generator for realm vocabularies

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#143]
Once CMIP6 realms specialisations have settled down, generate mindmaps for futher interaction with community. Start with ocean

**Comment by murphysj** [comment]
@momipsl Can this be closed?

**Comment by eguil** [comment]
Yes, I think this can be closed

**Comment by eguil** [comment]
I also had to extend the compact of some sub-process to classic as they were not pick up by the mm generator

**Comment by eguil** [comment]
add change history
