### ISSUE TITLE
Create and review a Conformance Workflow diagram

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#144]
Some things to consider:

a) Who will create the CIM2 classes
b) How will the documents be generated (e.g. the Questionnaire??)
c) What other documents will conformances link to and what other documents (e.g. experiments) will link to conformances.
d) where in the pipeline will baseline cim document info be added (e.g. UID)

**Comment by charliepascoe** [comment]
First thoughts on Conformances
![conformancethoughts](https://cloud.githubusercontent.com/assets/3264143/16307062/d2b7be2a-3957-11e6-8d88-56fc0613bc45.jpg)

**Comment by charliepascoe** [comment]
Link to conformance stuff in the CIM
https://github.com/ES-DOC/esdoc-cim/blob/master/v2/schema/activity_classes.py

**Comment by charliepascoe** [comment]
Note that when I refer to "requirement" I mean any kind of numerical requirement which generally means forcingConstraint but can also refers to other kinds of requirements such as ensemble_requirement or the general requirement class.

**Comment by murphysj** [comment]
Charlotte,

Question 1: Are the requirement standalone cim documents or are they just
attributes of the experiment?

When we talk about linking documents, what this really means is putting a
construct in the "XML" of one document that points to the the ID of
another.

I am trying to figure out where the IDs to the conformances will live.


Question 2: when you say spreadsheet, do you image esdoc pre-populating a
spreadsheet for each modeling group to fill in that would only have their
stuff?



On Thu, Jun 23, 2016 at 8:39 AM, Charlotte <notifications@github.com> wrote:

> Note that when I refer to "requirement" I mean any kind of numerical
> requirement which generally means forcingConstraint but can also refers to
> other kinds of requirements such as ensemble_requirement or the general
> requirement class.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/144#issuecomment-228071148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABcVAP4vuv2znRdtLK8yL7fa66Vz8XYbks5qOpqkgaJpZM4IfhUO>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by charliepascoe** [comment]
Answer 1.
Requirements are stand-alone CIM documents and not simply attributes of experiments.  
Each requirement will have a doc-id associated with it, as will each conformance.

Answer 2.
As fas as CIM 2 stands at the moment a conformance document has a description and a status.
The description is free text.
The status is selected from the enumeration: 
Conformed / Partially Conformed / Not Conformed / Not Applicable.

It doesn't really matter how we capture this information but it seems to me that a spreadsheet would keep things simple.  But conformances could just as easily be auto-generated by the groups, or captured in a web-form that we provide, or from a google doc spreadsheet...

The important thing is to ensure that we link the Requirement docs with their associated Conformance docs.

**Comment by davidhassell** [comment]
I've just being looking at Mark Elkington's proposal on this from ~1 year ago: https://files.slack.com/files-pri/T0LCK0NKV-F196XR3QF/forcingsnotes.pdf

Should we be updating the CIM for the items listed in section "Simulation Forcings Applied" (pages 3 and 4)?

**Comment by murphysj** [comment]
@davidhassell 

I think this document should be reviewed line by line on a call...hopefully the next one on 6/28. We should be confirming that the current experimental requirements take some of these things into account.

**Comment by davidhassell** [comment]
![conformance_workflow_v1](https://cloud.githubusercontent.com/assets/8126576/16733092/0b9ed628-4778-11e6-9aa7-79d4445f2127.png)

A first picture of a workflow

**Comment by davidhassell** [comment]
![conformance_workflow_v2](https://cloud.githubusercontent.com/assets/8126576/16913444/46b2d560-4ce2-11e6-9d8f-d8c1bf046f06.png)
Added that **Models** should be listed in an attribute of the Conformance document.

**Comment by davidhassell** [comment]
For the record, the forcings table 12.1 from IPCC AR5 is [table_12.1.pdf](https://github.com/ES-DOC/esdoc-docs/files/371347/table_12.1.pdf)

Charlotte - I think that I might be missing some information. E.g for "Pre-Industrial Land Use", where can I find out exactly what the "constant pre-industrial land-ise forcing" has to actualy be?

Thanks, David

**Comment by charliepascoe** [comment]
The forcing that needs to be conformed to should be described by the forcing constraint (requirement).
In the specific case of land use forcing, CMIP6 provides a historical land use data set, but no specific pre-industrial data set. So I've linked to the reference for the historical land use data set in the pre-industrial land use forcing constraint. I have assumed that the historical data begins in pre-industrial period (1850  or there about).
By the time we get to the end of the review process all the requirements should be clearly specified.

**Comment by davidhassell** [comment]
OK, that makes sense. Thanks.

In order to auto-generate table 12.1, I'm getting the feeling that we will need a conformance specialisation for each numerical requirement, so that table 12.1 questions like "Was CO2 forcing applied (Y/N)" can be answered. I don't think answers to such questions can be inferred from the forcing constraints (?). This idea is still embryonic.
