### ISSUE TITLE
In the Viewer, see the range of possible values along with the value chosen 

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#15]
WHO: Eric

CIM documents coming out the Metafor questionnaire have just what the user selected. In order to help modeling groups QC their input, see the possible values at the same time would be useful.

Perhaps as a pop-up since it will really muck up the display.

**Comment by momipsl** [comment]
@davidhassell Is this still required

**Comment by davidhassell** [comment]
Hi Mark,

I'll discuss this with Eric tomorrow (2015-03-26) and get back to you.

David

**Comment by murphysj** [comment]
From Eric and David:

Two reason to potentially still do this:

1) We don't know what the CMIP6 QC process will be like
2) For context, it may be useful to list the other values so people can see how things compare

**Comment by davidhassell** [comment]
Out of scope for CMIP6
