### ISSUE TITLE
Be able to customize the search facets in the CIM Search by project

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#16]
WHO: Christiane Jablonowski

Projects using the CIM since CMIP5 have added new properties to their CIM documents. They want to be able to search for those specific attributes.

**Comment by momipsl** [comment]
This use case is better served using the comparator.  I.E. open the comparator; select properties of interest; see documents.

**Comment by murphysj** [comment]
This will be solved when #3 is completed.
