### ISSUE TITLE
Be able to search for and display metadata from multiple sources

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#17]
WHO: Dev Team

Model documentation lives in CIM records, DRS facets, netCDF attributes etc. An ability to pull all this metadata together, search for it, and display it will be the next generation of metadata services.

**Comment by momipsl** [comment]
New pyescv library is first step towards this.

**Comment by murphysj** [comment]
This requirement came from a project that no longer exists. They were
anticipating model metadata existing in various formats.  We have enough to
do to handle the CIM.

I would label this no longer applicable and close it.

On Tue, Mar 24, 2015 at 8:06 AM, Mark A. Greenslade <
notifications@github.com> wrote:

> New pyescv library is first step towards this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/17#issuecomment-85509226>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
