### ISSUE TITLE
user defined search for experiment names

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#170]
Allow users to define their own search terms rather than confining search to a selection from a drop-down list.  This will be of particular use for users who want to find information about specific experiments which may have had different names in past incarnations. 
I would allow users to enter their own search terms to query the following fields: 
- name
- long_name 
- canonical_name 
- other_names

**Comment by momipsl** [comment]
irrelevant now that search by MIP exists
