### ISSUE TITLE
Ocean biogeochemistry specialisation review for CMIP6

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-docs#171]
---------- Forwarded message ----------
From: <martin.juckes@stfc.ac.uk>
Date: 14 January 2016 at 14:43
Subject: CMIP6 model documentation ... a requirement from the VIACS AB MIP
To: bryan.lawrence@ncas.ac.uk, charlotte.pascoe@stfc.ac.uk, mark.elkington@metoffice.gov.uk, sebastien.denvil@ipsl.jussieu.fr

Hello Bryan, Charlotte, Mark, Sébastien,

I'd like to pass on a request for some model documentation from the VIACS AB group. They originally asked for it as part of the data request, but I think it belongs in ES-DOC:
* size range for phytoplankton;
* size range for zooplankton.

Can this be added in? (Or is it already in?)

cheers,
Martin

________________________________
From: RUANE, ALEXANDER C. (GISS-6110) [alexander.c.ruane@nasa.gov]
Sent: 15 December 2015 17:11
To: Juckes, Martin (STFC,RAL,RALSP)
Cc: Claas Teichmann
Subject: FW: Questions on ocean variables requested via the VIACS AB

Dear Martin,

Please see below for responses on the variable questions you asked.  Please let us know if you have further questions or require more extensive clarifications.

From our side, Alex Ruane will be happy to contribute as the VIACS Advisory Board co-author on the Variable Request paper you are writing.

     Best regards,
          -Alex and Claas (co-chairs of the VIACS Advisory Board)

--
=====================
Dr. Alex C. Ruane
Research Physical Scientist, Climate Impacts Group, NASA GISS
2880 Broadway
New York, NY 10025
+001 212-678-5640
alexander.c.ruane@nasa.gov
________________________________
With input from: Heike Lotze [Heike.Lotze@Dal.Ca], Derek Tittensor (Derek.Tittensor@unep-wcmc.org); James Watson (james.watson@su.se); and olivier.maury@ird.fr

[From Martin Juckes]:
>
> There are a few more questions I have on the new variables list:
>
> (1) Wind speed and direction on model levels: wind vectors on model levels will be stored for other MIPs. Presumably this will be good enough. I don't think we can justify storing wind components and the same information as speed and direction.
VIACS AB: Agreed -- no need to store speed and direction if vectors are provided

>
> (2) There is a request for depth resolved primary productivity. In the CF standard names there is a variable "net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_phytoplankton" defined as follows:
> "Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. Net primary production is the excess of gross primary production (rate of synthesis of biomass from inorganic precursors) by autotrophs ("producers"), for example, photosynthesis in plants or phytoplankton, over the rate at which the autotrophs themselves respire some of this biomass. "Productivity" means production per unit area. Phytoplankton are autotrophic prokaryotic or eukaryotic algae that live near the water surface where there is sufficient light to support photosynthesis. The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A."
>
> Is this the variable wanted?
VIACS AB: If this is net primary productivity (NPP) expressed as mol carbon (rather than biomass), than this is fine. If not, then we would need to know exactly what it is.

>
> (3) Mass ranges for phyto and zoo plankton: I think this will have to be a request for model documentation information rather than part of the data request, because it is information about the configuration of the model rather than the output .. I'll pass it on.
VIACS AB: Agreed – this should be in the model documentation!

>
> (4) "large particulate carbon concentration": what is meant by large here? There are 4 related standard names in the existing table:
> mole_concentration_of_particulate_matter_expressed_as_silicon_in_sea_water
> mole_concentration_of_particulate_organic_matter_expressed_as_iron_in_sea_water
> mole_concentration_of_particulate_organic_matter_expressed_as_nitrogen_in_sea_water
> mole_concentration_of_particulate_organic_matter_expressed_as_phosphorus_in_sea_water
> and OMIP are applying for a variable name "Particulate Organic Carbon Content", which will be the carbon equivalent of the last 3. Do you think the new OMIP variable will be what is wanted?
VIACS AB: Biogeochemical models usually represent one or two size classes of particulate carbon (detritus). If there is only one size-category of "Particulate Organic Carbon Content", we can use that; however, we could also use two (small, large) if available.
>
> For the other variables I think the naming of the variable and the standard name are OK, apart from Euphotic depth, PAR, and evapotranspiration which we have discussed earlier.
VIACS AB: Please let us know if further information is required here.

-- 

Bryan Lawrence
University of Reading: Professor of Weather and Climate Computing.
National Centre for Atmospheric Science: Director of Models and Data.
STFC: Director of the Centre for Environmental Data Analysis.
Ph: +44 118 3786507 or 1235 445012; Web:home.badc.rl.ac.uk/lawrence

**Comment by allynt** [comment]
This issue was moved to ES-DOC/cmip6-specializations-ocean-bgc#2
