### ISSUE TITLE
The "refine your search" text on the CIM Archive page looks like a button

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#18]
WHO: Eric

This text is highlighted in yellow. It looks like a button (e.g. clickable). Modify. 

Bounce design off of Eric.

**Comment by murphysj** [comment]
I do not see any change on the search page for this item. On our call, you thought you had done this. If not, just move out of this release.

**Comment by momipsl** [comment]
Goto the search page.  Select Project=cmip5; Doc Type=Simulation;  Institute=IPSL.  This will return no records and the "Search returned no results -  please refine criteria" message is displayed in a huge banner.  See attached scennshot.
![esdoc-search-null](https://cloud.githubusercontent.com/assets/1267479/6936456/b29e14a2-d852-11e4-8bac-f8fd45d9f015.png)

**Comment by murphysj** [comment]
Perhaps I have misunderstood the issue. See attached screenshot of the search landing page.
There is a orange box right after the search results that says "refine your search". It looks like a button but is not clickable but look like it should be. 

![refine](https://cloud.githubusercontent.com/assets/1512704/6943451/63432066-d84b-11e4-8493-82af1da12520.png)

**Comment by momipsl** [comment]
OK the confusion was on my part.  Will display a brief message that will hide itself after 3 seconds or so.

**Comment by murphysj** [comment]
why don't we move this ticket out of this release so it does not delay
anything. It might be worth a 5 minute telco to discuss things.



On Wed, Apr 1, 2015 at 10:07 AM, Mark A. Greenslade <
notifications@github.com> wrote:

> OK the confusion was on my part. Will display a brief message that will
> hide itself after 3 seconds or so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/18#issuecomment-88535781>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by momipsl** [comment]
moved to 0.9.3

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#14
