### ISSUE TITLE
Write CIM2 Simulation

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#190]

**Comment by davidhassell** [comment]
Code to pull information out of CMIP5 and CMIP6 netCDF files has been written - https://github.com/ES-DOC/esdoc-cdf2cim/tree/master/netCDF2cim 

Next step is to use pyesdoc to parse this info into CIM2 Simulation/Ensemble/EnsembleMember documents and publish or republish them, depending on whether or not they have already been created.

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-cim#27
