### ISSUE TITLE
Add "scope" to forcings/requirements in the CMIP6 experiments spreadsheet

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#220]
Scope allows us to categorise forcings/requirements in terms of how widely they are shared through CMIP6
1.  shared widely across CMIP6 e.g. "concentration of pre-industrial CO2" & "Impose AMIP SSTs".
2.  shared with companion MIPs e.g. aerosol forcing in GeoMIP and AerChemMIP.
3.  shared within a MIP e.g. spin-up protocol for land surface experiments in LUMIP.
4.  is applied to a single experiment e.g. CFMIP "zonally uniform SST plus 4K"

**Comment by charliepascoe** [comment]
Is related to this
https://github.com/ES-DOC/cmip6-specializations-toplevel/issues/6

**Comment by charliepascoe** [comment]
90% complete.  
I've added scope and order metrics to the forcing constraints (as of version 51).  
Scope metrics are internally consistent with the cmip6-experiments database.  
Order metrics will need to be reviewed by the MIP teams.

**Comment by charliepascoe** [comment]
Completed scope and order metrics for forcing constraints.  
Note that the order metrics (which indicate whether conformance info can be provided before an experiment is simulated) will need to be reviewed by MIP teams.

**Comment by momipsl** [comment]
I have extended the CIM to include a [scope attribute upon the NumericalRequirement](https://github.com/ES-DOC/esdoc-cim/blob/master/v2/schema/designing_classes.py#L237-L238) class.

**Comment by momipsl** [comment]
Can you please clarify what the Order

**Comment by charliepascoe** [comment]
The order column refers to a concept that Mark E introduced. It refers to whether conformance information can be provided before simulations have been run (order 1) or can only be provided from diagnostic information after the simulations have been performed (order 2).

**Comment by charliepascoe** [comment]
The scope metrics are useful in terms of communicating to the modelling groups the completeness of the conformance information that they've provided to us.  And indicating which forcing constraints are applicable to the widest number of experiments.   Likewise the order metric is useful in terms of assessing when the modelling teams need to consider giving us conformance information. But I'm not sure how useful they'll be to the public as a whole once the metadata has been collected.

**Comment by charliepascoe** [comment]
Given that the es-doc viewer is the main tool we plan to use to communicate with MIP teams, modelling groups and the wider user community I think we do need to render both scope and order metrics even though they may not be of much use in the long term.

**Comment by momipsl** [comment]
Closed for scope still open for order pending conversation between Mark E and Charlotte.
