### ISSUE TITLE
Don't capitalise the first letter of experiment names

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#222]
The experiment name that appears in the top of the banner of a CMIP6 experiment page has the first letter capitalised.  We need to stop doing that.

All CMIP6 experiment names either begin with a lower case letter or a number so the capitalisation of the first letter of the experiment name in our interface appears to be a mistake on our part.

This issue lies somewhere between bug and feature request so I've labelled with both.

<img width="1392" alt="es-docexpname" src="https://cloud.githubusercontent.com/assets/3264143/19928317/db753816-a0f5-11e6-8419-e931d21895d6.png">

**Comment by momipsl** [comment]
Have removed **text-transform: capitalize;** instruction from relevant CSS file.  Will push to PROD either today or tomorrow.
