### ISSUE TITLE
Experiment forcing constraints appear in a random order

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#223]
An experiment's forcing constraints appear in a random order in the es-doc interface.  I would prefer that they be shown to users in the order that they are listed in the cmip6-experiments spreadsheet. 

I have used a systematic approach to the listing of forcing constraints such that either the most relevant forcings are listed first or the forcings of related experiments are listed in the same order.  We lose some semantic inference if the forcings are presented randomly.

At the very least, if a requirement has been used to group together related forcing constraints these forcing constraints should be listed concurrently (e.g. requirement 8: historical solar forcing).

**Comment by momipsl** [comment]
OK will update the spreadsheet processing script next Monday.

**Comment by momipsl** [comment]
This has been implemented.  The constraints were being sorted alphabetically so this was initally simple.  But then ensuring that the grouped constraints were also being listed correctly was a little trickier.
