### ISSUE TITLE
Ensure that experiment tier is extracted from spreadsheet

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#227]
The experimental tier (1 | 2 | 3 | n) can be derived from the 2nd keyword in the CMIP6 experiment spreadsheet.  When linking projects to experiments we can add a quailifier (mandatory | optional) which is useful information.

**Comment by charliepascoe** [comment]
Still not sure about mandatory/optional terminology given that the tier system is well understood by the CMIP6 community.  Think it is better to simply list experiments by tier.

**Comment by charliepascoe** [comment]
Suggest we use headings of the form:
<project> <tier> experiments
e.g.
C4MIP Tier 1 experiments
C4MIP Tier 2 experiments

**Comment by charliepascoe** [comment]
We also need a heading for experiments that are required but are defined by other MIPs.
e.g.
Experiments required from other MIPs

**Comment by charliepascoe** [comment]
Note an initial reaction from the ScenarioMIP Pis to list experiments by tier rather than as a straight list of required experiments.

**Comment by momipsl** [comment]
Tier is being extracted - I added a new attribute to the NumericalExperiment class.

**Comment by momipsl** [comment]
Just need to exclude governed experiments from list of required experiments

**Comment by charliepascoe** [comment]
worksforme
