### ISSUE TITLE
Expand experiment relationships

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#229]
Experiments can have related experiments.
These relationships are specified https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/master/designing_classes.py#L200-L223
So an experiment can be related to another experiment in different ways.

Right now I only list experiments once, but in reality an experiment can be both a parent and a control (as in the case of the piControl).  

Need to expand the listing of experiment relationships because experiments can be listed more than once.

**Comment by charliepascoe** [comment]
Done in my local copy, will be in next update.

**Comment by charliepascoe** [comment]
Note that I have updated the experiment relationship headings for consistency with the CIM

**Comment by momipsl** [comment]
Implemented

**Comment by charliepascoe** [comment]
Worksforme but I won't close yet as this is a note for me to provide content.

**Comment by charliepascoe** [comment]
I don't think that it is a priority to add additional experiment relationships at this stage.  
It is more important to check that we have consistency across CMIP6-CV, ES-DOC and the MIP's GMD papers for the "parent experiment id"/"is_initialized_by" field which is taken on in issue #284
