### ISSUE TITLE
RFMIP: party missing from project and experiment records

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#232]
Robert Pincus is missing from the rendered list of parties on the RFMIP project record.
I looked at a random experiment record (hist-spAer-all) and found that he is also missing from that. 

http://documentation.es-doc.org/cmip6/mips/rfmip

**Comment by momipsl** [comment]
Can confirm that this is a relatively minor collection indexing related issue

**Comment by momipsl** [comment]
Implemented

**Comment by charliepascoe** [comment]
worksforme
