### ISSUE TITLE
Re-order the HighResMIP objectives

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#235]
http://documentation.es-doc.org/cmip6/mips/highresmip

The HighResMIP PI has requested that we re-order the list of objectives to better reflect the priorities of the HighResMIP.

1 -> 8
2 -> 6
3 -> 3
4 -> 1
5 -> 4
6 -> 7
7 -> 2
8 -> 5

**Comment by charliepascoe** [comment]
Martin tells me that the objectives should be considered arbitrary so would be better to present these as an unordered list.

**Comment by charliepascoe** [comment]
The order of the objectives as presented on the es-doc interface is the same as that of the list on the cmip6 data request.  I propose that any re-ordering of objectives be done at the cmip6dr end and not by us.

**Comment by charliepascoe** [comment]
Have asked Martin to resove this.
https://github.com/cmip6dr/Request/issues/20

**Comment by martinjuckes** [comment]
HighResMIP has 7 objectives ... I need to know how these seven should be re-ordered:
Large scale
small scale
Extreme events
Tropical cyclones
Ocean
Diurnal cycle
Process studies
