### ISSUE TITLE
Permanent urls have "Bad Gateway" error

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#236]
We're seeing 502 - Bad Gateway errors on the permanent urls that we gave to the MIP teams to review the CMIP6 experiment documentation
e.g. http://documentation.es-doc.org/cmip6/mips/scenariomip

**Comment by esdoc-system-user** [comment]
Web host rebooted machines over the holidays.  I simply had to restart the URL rewriting web-service.  However I will try to write a machine startup script that will auto-start this service if the machine is rebooted.
