### ISSUE TITLE
Present MIP objectives as an unordered list 

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#239]
The MIP objectives as listed in the CMIP6 data request are presented as unordered lists.
For consistency es-doc should present the MIP objectives in the same way because numbering objectives implies some kind of prioritisation. The CMIP6 data request intends for objectives to be considered as a flat list.

**Comment by momipsl** [comment]
Implemented

**Comment by momipsl** [comment]
Implemented

**Comment by charliepascoe** [comment]
worksforme
