### ISSUE TITLE
Do not render "delivery order" for forcing constraints

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#244]
I don't think we need to give users the "delivery order" information in the es-doc interface.
Mark Elkington was of the view that all forcing constraints would have a pre-simulation delivery order anyway.  I think this piece of information doesn't add much to the understanding of what the forcing constraint is about and if nearly all FCs have the same status it's a waste of screen real estate.

**Comment by momipsl** [comment]
Implemented

**Comment by charliepascoe** [comment]
worksforme
