### ISSUE TITLE
Capture when extra information is needed for conformances

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#251]
We want to know which forcing constraints will need extra information from users when they come to tell us about the associated conformances.
I have repurposed column D in the forcing_constraint tab to hold True/False info about whether further info will be needed from the modelling groups to complete conformances.  For the time being this column is titled "info_required".
Mark will likely have to update his code to accommodate this change.

**Comment by momipsl** [comment]
Have added a new attribute to the NumericalRequirement class: is_conformance_info_required

**Comment by charliepascoe** [comment]
Good enough for me
