### ISSUE TITLE
Make clear when forcings are grouped into requirements in the online documentation

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#262]
In some instances forcings are grouped for convenience but at other times there is often some semantic info to the grouping.  
An example of semantic grouping is the LUMIP requirement: trendySpinUpGSWP3.  
When grouped it is clear that the trendySpinUpGSWP3 forcing constraints are all to do with the spin-up forcing characteristics of the experiment but when they are viewed separately they confuse users because some of the spin-up forcings appear to contradict the forcings required by the main body of the experiment.
So we need some way of indicating when forcings have been grouped together into a requirement in the online interface.

**Comment by davidhassell** [comment]
Is the grouping made by the `numerical_requirements.requirements` property (https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/master/designing_classes.py#L192) so in a group, say, 4 requirements each one references the other 3?

**Comment by charliepascoe** [comment]
Suggested to use indenetation to signify when forcings have been grouped into a requirement.

**Comment by charliepascoe** [comment]
David:  I've been strict in how I've applied the groupings so requirements that group forcings in the CMIP6 spreadsheets only contain forcing requirements

**Comment by charliepascoe** [comment]
Added semantic_reasoning column to the requirements tab (column Q) and set to TRUE where requirements are grouped for some meaningful purpose.
