### ISSUE TITLE
Inconsistencies with CMIP6 Experiments CV

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/esdoc-docs#265]
@charliepascoe Compared with the experiment name vocabulary at https://github.com/WCRP-CMIP/CMIP6_CVs , on May 19th, I found the following differences:
3 experiments match with some change of case (ES-DOC first): 
{u'sspXY': u'sspxy', u'land-noShiftcultivate': u'land-noShiftCultivate', u'amip-p4k-lwoff': u'amip-p4K-lwoff'}
9 experiments I have matched based on name similarity (CMIP6 CV first this time):
{u'dcppC-ipv-minus': u'dcppC-ipv-neg', u'dcppC-amv-trop-minus': u'dcppC-amv-Trop-neg', u'dcppC-pac': u'dcppC-pac-control', u'dcppC-amv-trop-plus': u'dcppC-amv-Trop-pos', u'dcppC-amv-extrop-minus': u'dcppC-amv-ExTrop-neg', u'dcppC-amv-minus': u'dcppC-amv-neg', u'dcppC-amv-plus': u'dcppC-amv-pos', u'dcppC-amv-extrop-plus': u'dcppC-amv-ExTrop-pos', u'dcppC-ipv-plus': u'dcppC-ipv-pos'}

There are then 3 ES-DOC and 30 CMIP6 CV experiments which don't match. From ES-DOC:
C4MIP  [u'ssp534-over-bgcExt', u'ssp585-bgcExt']
VolMIP  [u'volc-pinatubo-ini']
From CMIP6 CV:
DCPP  [u'dcppA-assim', u'dcppC-ipv-NexTrop-neg', u'dcppC-ipv-NexTrop-pos']
AerChemMIP  [u'piClim-NH3', u'piClim-OC', u'piClim-SO2', u'ssp370-lowNTCF', u'ssp370SST', u'ssp370SST-lowAer', u'ssp370SST-lowBC', u'ssp370SST-lowCH4', u'ssp370SST-lowNTCF', u'ssp370SST-lowO3', u'ssp370SST-ssp126Lu']
ISMIP  [u'ism-asmb-std', u'ism-bsmb-std', u'ism-ctrl-std']
LS3MIP  [u'lfmip-pdL-princeton', u'lfmip-pdLC-cruNcep', u'lfmip-pdLC-wfdei', u'lfmip-rmLC-cruNcep', u'lfmip-rmLC-princeton', u'lfmip-rmLC-wfdei']
CMIP  [u'esm-piControl-spinup', u'piControl-spinup']
HighResMIP  [u'highresSST-4co2', u'highresSST-LAI', u'highresSST-p4K', u'highresSST-smoothed', u'spinup-1950']

**Comment by charliepascoe** [comment]
@martinjuckes 
I'll take a look at the case discrepancies, I don't believe that Mark's code checks for case.

As it happens I've been working on the ES-Doc experiment info today and the other ES-Doc naming discrepancies you list have been corrected as of version 76 of the CMIP6_Experiments spreadsheet.

These dcpp experiment names have been updated in ES-Doc:
9 experiments I have matched based on name similarity (CMIP6 CV first this time):
{u'dcppC-ipv-minus': u'dcppC-ipv-neg', u'dcppC-amv-trop-minus': u'dcppC-amv-Trop-neg', u'dcppC-pac': u'dcppC-pac-control', u'dcppC-amv-trop-plus': u'dcppC-amv-Trop-pos', u'dcppC-amv-extrop-minus': u'dcppC-amv-ExTrop-neg', u'dcppC-amv-minus': u'dcppC-amv-neg', u'dcppC-amv-plus': u'dcppC-amv-pos', u'dcppC-amv-extrop-plus': u'dcppC-amv-ExTrop-pos', u'dcppC-ipv-plus': u'dcppC-ipv-pos'}

These experiments from the ES-Doc list (renamed as "n/a")
C4MIP [u'ssp534-over-bgcExt', u'ssp585-bgcExt']
VolMIP [u'volc-pinatubo-ini']

**Comment by charliepascoe** [comment]
Latest update is now consistent with the experiment names in the list maintained at PCMDI for the WCRP
