### ISSUE TITLE
Some spelling mistakes in ES-DOC experiment descriptions

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/esdoc-docs#267]
@charliepascoe I've run the experiment descriptions through a spelling check and found the following:

u'amomaly', u'atmoshere', u'atmospehere', u'behavior', u'beolow', u'chmeistry',  u'condtions', u'depleating',  u'diriven', u"experient's", u'focing', u'halvinging', u'helt',  u'impoased',  u'magnitued',  u'negaitive',  u'ocurred', u'pertubation', u'pre-inudsutrial', u'precurors',  u'quadruping', u'reches', u'simulaitons', u'suface', u'unchaged', 

I hope you can trace them by searching ..  

There are also a number of cross-references to experiments .. but I haven't checked all those yet.

**Comment by charliepascoe** [comment]
Thanks for raising this issue.  I think I've captured all the spelling errors and typos now.
