### ISSUE TITLE
Conformance Requested/Required?

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#268]
At the moment we have two similar fields on the web interface for forcing constraints:
Is conformance requested?
Is conformance info required?
but we don't need them both.

It is not necessary to render the "Is conformance requested?" field, even if the "is conformance info required?" field is not present.

We do need to render the "Is conformance info required?" field but it would be better to re-word it.  
I suggest we use the following text:
"Conformance description needed?"

If we ever have a hover-over option for additional help text it should read:
"Modelling groups must provide a conformance description for this requirement" 

<img width="989" alt="screen shot 2018-01-11 at 15 52 15" src="https://user-images.githubusercontent.com/3264143/34833608-bdca47c2-f6e7-11e7-9594-55dcf3f9939d.png">

Note that the "sucha" typo in this example was corrected at version 85 of the CMIP6_Experiments spreadsheet.

**Comment by momipsl** [comment]
OK will implement this change and release it along with latest experiments before next telco

**Comment by momipsl** [comment]
@charliepascoe Can you confirm whether I can also remove the 'Is Conformance Requested ?' field for the other numerical requirements such as EnsembleRequirement, MultiEnsemble, TemporalConstraint ...etc.

**Comment by charliepascoe** [comment]
yes you can remove the "is conformance requested?" field for all numerical requirements.

**Comment by momipsl** [comment]
ok
