### ISSUE TITLE
Version id/status for the CMIP6 experiment documentation

### ISSUE THREAD

**Issue by charliepascoe** [ES-DOC/esdoc-docs#269]
Given the federated nature of the CMIP6 project with individual MIPs being coordinated by different science teams it is likely that iterations to the ES-DOC experiment documentation will occur on a MIP by MIP basis.  Therefore it makes sense to come up with a versioning/status system that reflects this modularity rather than the gobal method that has been used until now.

**Comment by eguil** [comment]
Mark looking at cheksums to update date + version

**Comment by eguil** [comment]
Charlotte to start v1 in dec release of doc and work out new releases and dates.
Add these in master spreasheet per MIP and to be rendered in viewer ("Last update" and "Version")

**Comment by davidhassell** [comment]
Moved to https://github.com/ES-DOC/esdoc-project/issues/68
