### ISSUE TITLE
Add the IS-ENES logo to the Splash Page

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#27]
WHO: Eric

**Comment by momipsl** [comment]
Could not find a transparent logo therefore reluctant to include

**Comment by SebastienDenvil** [comment]
This is feasible sooner that 0.9.5 I believe. Send me the logo you selected and I will provide you with a transparent logo. It should be in 0.9.2 actually.

**Comment by momipsl** [comment]
I tried to use these logos pulled from the IS-ENES site:
https://github.com/ES-DOC/esdoc-splash/blob/master/src/assets/img/enes-logo-1.png
https://github.com/ES-DOC/esdoc-splash/blob/master/src/assets/img/enes-logo-2.png

**Comment by murphysj** [comment]
I was under the impression that the Splash page was up for removal, to be
replaced by a wordpress blog site. This came out of the February meeting
n'est pas?

While this would we quick to do, I am not sure it buys us much if no one is
going to the site and we are going to get rid of it.

On Wed, Mar 25, 2015 at 8:11 AM, Mark A. Greenslade <
notifications@github.com> wrote:

> I tried to use these logos pulled from the IS-ENES site:
>
> https://github.com/ES-DOC/esdoc-splash/blob/master/src/assets/img/enes-logo-1.png
>
> https://github.com/ES-DOC/esdoc-splash/blob/master/src/assets/img/enes-logo-2.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/27#issuecomment-86044698>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by momipsl** [comment]
Your impression may be erroneous at this point in time.  The blog could certainly be used to replace the splash but there again the splash could be updated to include a link to the blog.  Again food for more discussions at next F2F.  Regardless having the ENES logo visible is a requirement in the short term.

**Comment by murphysj** [comment]
Ok, then move this ticket into 0.9.3

On Wed, Mar 25, 2015 at 9:21 AM, Mark A. Greenslade <
notifications@github.com> wrote:

> Your impression may be erroneous at this point in time. The blog could
> certainly be used to replace the splash but there again the splash could be
> updated to include a link to the blog. Again food for more discussions at
> next F2F. Regardless having the ENES logo visible is a requirement in the
> short term.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/27#issuecomment-86080438>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by SebastienDenvil** [comment]
see attached.

Le 25/03/2015 16:22, Sylvia Murphy a écrit :
> Ok, then move this ticket into 0.9.3
>
> On Wed, Mar 25, 2015 at 9:21 AM, Mark A. Greenslade <
> notifications@github.com> wrote:
>
> > Your impression may be erroneous at this point in time. The blog could
> > certainly be used to replace the splash but there again the splash 
> could be
> > updated to include a link to the blog. Again food for more 
> discussions at
> > next F2F. Regardless having the ENES logo visible is a requirement 
> in the
> > short term.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ES-DOC/esdoc-docs/issues/27#issuecomment-86080438>.
> >
>
>
>
> -- 
> ******************************************
> Sylvia Murphy
> NESII/CIRES/NOAA Earth System Research Laboratory
> 325 Broadway, Boulder CO 80305
> Time Zone: U.S. Mountain
> Web: http://www.esrl.noaa.gov/nesii/
> Email: sylvia.murphy@noaa.gov
> Phone: 303-497-7753
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/27#issuecomment-86080683>.
>


-- 
Sébastien Denvil
IPSL, Pôle de modélisation du climat
UPMC, Case 101, 4 place Jussieu,
75252 Paris Cedex 5

Tour 45-55 2ème étage Bureau 209
Tel: 33 1 44 27 21 10
Fax: 33 1 44 27 39 02

**Comment by momipsl** [comment]
I have added this logo to the splash page.  Also added NSF, NOAA and IPSL logos.  Will bundle this into the 0.9.2 deployment - therefore milestone has been updated.

**Comment by murphysj** [comment]
verified on test server. closing.
