### ISSUE TITLE
Model configuration ... consistency with CVs.

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/esdoc-docs#272]
The CMIP6 experiment_id CV has `required_model_components` and `additional_allowed_model_components` which provide information about model configuration(s) needed for each experiment. This should, I think, be consistent with the ES-DOC `model_configuration` attribute. Since the information is presented differently, it is not obvious what the mapping should be, but the most widely used configuration ia `AOGCM configuration` which matches well with `required:AOGCM + additional:AER BGC CHEM`, with 100 experiments matching correctly. There are 9 that don't match (listed below). Beyond that it gets confusing. `AGCM configuration` and `Atmosphere-Land configuration` match `required:AOGCM + additional:AER BGC CHEM` and `required:AOGCM + additional:AER CHEM`  --- but there is some cross-over between the two ES-DOC categories and the two pairs of categories, so it is not clear to me whether `AGCM configuration` should match `required:AOGCM + additional:AER BGC CHEM` or `required:AOGCM + additional:AER CHEM` (or perhaps it is a different categorisation and is not intended to match either).

There is some additional discussion here: https://github.com/WCRP-CMIP/CMIP6_CVs/issues/604 

Here are some details:

>  -- AOGCM Configuration & AOGCM required, AER, BGC, CHEM allowed -- 
Experiments matching: 100
AOGCM ... esdoc only:
    hist-1950 control-1950 highres-future:: required: AOGCM; allowed: AER
    hist-stratO3 ssp245-stratO3:: required: AOGCM; allowed: AER BGC
    hist-spAer-aer hist-spAer-all:: required: AOGCM; allowed: 
AOGCM ... CV only: 
    hist-resAMO hist-resIPO:: CGCM Configuration

> -- AGCM Configuration & AGCM required, AER, CHEM allowed -- 
Experiments matching: 31
AGCM ... esdoc only:
    highresSST-p4K highresSST-present highresSST-smoothed highresSST-4xCO2 highresSST-LAI highresSST-future:: required: AGCM; allowed: AER
    spinup-1950:: required: AOGCM; allowed: AER
    amip-climSST amip-lfmip-pObs amip-lfmip-pdLC pdSST-piAntSIC pdSST-futAntSIC modelSST-futArcSIC pdSST-futArcSIC pdSST-futArcSICSIT pdSST-pdSIC pdSST-futBKSeasSIC pdSST-piArcSIC pdSST-futOkhotskSIC piSST-piSIC piSST-pdSIC amip-lfmip-rmLC futSST-pdSIC pdSST-pdSICSIT modelSST-pdSIC amip-climSIC amip:: required: AGCM; allowed: AER BGC CHEM
AGCM ... CV only:
    piClim-histall piClim-4xCO2 piClim-ghg piClim-anthro piClim-histnat piClim-lu piClim-histghg piClim-histaer:: Atmosphere-Land Configuration

**Comment by charliepascoe** [comment]
I have reviewed the ESDOC CMIP6 experiments with a view to achieving consistency between the ES-DOC and PCMDI model configuration descriptions or at least clear mappings. These are correct as of version 97 of the ES-DOC experiment spreadsheet. 
As a general rule the ES-DOC "model configuration" maps to the PCMDI "required model components".
I am recording the mappings in this google document
https://docs.google.com/spreadsheets/d/1ECfvY4RNAzmtrW1TKgMjHRq2-DFQ2htOSG5yXdCrfEs/edit#gid=0

**Comment by martinjuckes** [comment]
Hi Charlotte, that is a nice piece of work .. it is good to see a high level of consistency. Have you raised an issue with PCMDI about the "OMIP2 spinup" and "atmosphere land-surface" configurations?

**Comment by charliepascoe** [comment]
Not yet but I intend to later today.
