### ISSUE TITLE
Description of GeoMIP experiment G1 is circular.

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/esdoc-docs#273]
@charliepascoe : The description of GeoMIP experiment G1 starts with "Extended version of GeoMIP experiment G1". I think this refers to an earlier experiment G1 in an earlier GeoMIP. Can we re-word it?

**Comment by charliepascoe** [comment]
I tried to make it clear that I was referring to the G1 GeoMIP experiment in the Kravitz et al paper.  The full quote is: "Extended version of GeoMIP experiment G1 (Kravitz et al., 2011)."
I agree that the description is complicated by the fact that GeoMIP is both a CMIP6 MIP and a MIP that exists outside of CMIP6-land.  And that the G1 GeoMIP-land experiment is different to the G1 CMIP6-land experiment.

I think the solution will be to remove the first sentence from the G1 experiment description.  
It was there to provide context but if it's causing confusion it can go.  The description makes sense without it.
