### ISSUE TITLE
Should GMMIP extended AMIP experiment be defined without overlap?

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/esdoc-docs#274]
@charliepascoe : GMMIP has an extended AMIP experiment (`amip-hist`) from 1870 to 2014. This looks like the case you had with a CDRMIP experiment, where there is duplication over the shared part of the experiment. Do both `amip-hist` and `amip` need to be run from 1975 to 2014, or could `amip-hist` stop at 1974?

**Comment by charliepascoe** [comment]
I think not.
There's a subtle difference between these experiments in terms of the SSTs.
GMMIP specifies that HadISST should be used.
Whereas AMIP SSTs are "Merged SST based on UK MetOffice HadISST and NCEP OI2".
see https://pcmdi.llnl.gov/mips/amip/
Even if same SSTs were used in both experiments, given that we can assume that the modelling groups will run AMIP first, wouldn't there then be a discontinuity if we run amip-hist up to the end of 1974?
