### ISSUE TITLE
Incorrect years in experiment document citations

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-docs#275]
I believe (this needs checking) that: 
- Collins et al for aerochemmip is 2017 not 2016
- PMIP is Kageyama et al 2018 and the title changed on the way from GMDD to GMD.

**Comment by bnlawrence** [comment]
Also, Webb et al for CFMIP is 2017 (doi is correct, but not year in title string)

**Comment by charliepascoe** [comment]
Updated Collins et al 2017
PMIP info refers to Kageyama 2018
Updated Webb et al 2017
