### ISSUE TITLE
Outstanding tasks for public release of model documentation

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-docs#279]
# Essential tasks

## Spreadsheets

- [x] Finalize Citations spreadsheet format
- [x] Finalize Responsible Party spreadsheet format
- [x] Finalize Coupling spreadsheet format
- [x] Create final Citations spreadsheet 
- [x] Create final responsible Party spreadsheet 
- [x] Create final Coupling spreadsheet 
- [x] Organise repo according to description (https://es-doc.org/cmip6-layout-of-institutional-github-repositories/)
- [x] Fix discrepancy between model PDF and spreadsheet
- [x] Push final spreadsheets, of all varieties, to the institutional repositories

## Screencasts
- [x] Create all screencasts (at least ones for now)
- [x] Upload all screencasts to the youtube channel (https://www.youtube.com/channel/UCFVy0HC9cnGbIKc6UsDIHDA)
- [x] Upload all screencasts to wordpress

## Documentation
- [x] Review https://es-doc.org/cmip6-liaison-checklist/
- [x] Review https://es-doc.org/how-to/cmip6-layout-of-institutional-github-repositories/
- [x] Review https://es-doc.org/how-to-use-model-document-spreadsheets/
- [x] Review https://es-doc.org/how-to-use-model-citation-spreadsheets/
- [x] Review https://es-doc.org/how-to-use-model-responsible-party-spreadsheets/
- [x] Review https://es-doc.org/how-to-use-coupling-spreadsheets/
 
## Contacting the groups
- [x] Draft email to the PI mailing list
- [x] Send email to the PI mailing list
- [x] Draft email to individual liaisons (with CC to PIs)
- [x] Send email to individual liaisons
- [x] Create e-mail list of all ES-DOC liaisons

# Nice-to-have tasks

## Spreadsheets
- [x] add "Initialized by" and "Internal institute notes" rows to frontis of model spreadsheets [WON'T DO]

**Comment by momipsl** [comment]
Latest experiments have also been published
