### ISSUE TITLE
Provide tool context to the links on the Splash Page

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#28]
WHO: Sylvia

Currently the Splash Page contains links to the tools without any description of what they are. That information should exist either there or the resultant destination.

**Comment by momipsl** [comment]
An ES-DOC blog has been setup but articles on tools usage not yet created.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-api#11

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-web#25
