### ISSUE TITLE
Implementing CMIP5 experiments in CMIP6

### ISSUE THREAD

**Issue by martinjuckes** [ES-DOC/esdoc-docs#285]
There is a plan to add some CMIP5 experiments ( `historical`, `rcp45`, etc) to the CMIP6 experiment list, with modified names (`historical-cmip5`, `rcp45-cmip5`, etc) -- see [CMIP6 CVs #805](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/805). I'm raising the issue to give fair warning.

It is not clear  to me whether we can simply rely on the existing documentation or whether it might be easier in the long term to create new entries within the CMIP6 documentation, so that all the services work. I suspect the latter. We will need to ensure that `further_info_url` links from the files work.

**Comment by charliepascoe** [comment]
Moved this issue to https://github.com/ES-DOC/esdoc-project/issues/76
