### ISSUE TITLE
Enable the Comparator to compare CIM records with only a single model component

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#3]
WHO: DCMIP, ES-FDL, ESPS

There are several on-going projects that are producing CIM documents with only one document. 

Enable these to work in the Comparator.

**Comment by murphysj** [comment]
Note this is applicable to DCMIP, ESPS, ES-FDL, which are ongoing projects that have only one component documents.

**Comment by murphysj** [comment]
Considered top priority at the Feb 2015 F2F meeting.

**Comment by bnlawrence** [comment]
I don't see this as CMIP6 specific issue, so removing the label.

**Comment by murphysj** [comment]
yes, this is for DCMIP and ES-FDL, but not CMIP6

On Wed, Mar 2, 2016 at 2:59 AM, Bryan Lawrence <notifications@github.com>
wrote:

> I don't see this as CMIP6 specific issue, so removing the label.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/3#issuecomment-191165483>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#17
