### ISSUE TITLE
Create a Atom feed customizable by project

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#35]
WHO: Dev Team

Projects submit their CIM documents to the Archive via an Atom feed. Being able to see just their projects within that feed is useful.

**Comment by murphysj** [comment]
Currently, the way the questionnaire works is to set up feeds by project on that end. It may not be required for some universal feed that is controlled on the tools side.

**Comment by allynt** [comment]
I am unclear, is this still needed?  Currently, the Questionnaire feed can be restricted by project and document type.  I can add more if folks would like.

**Comment by prodiguer-git-user** [comment]
This ticket relates not to the questionnaire but to the ES-DOC API.  The API pulls together documents from various source as well as allowing 3rd parties to publish documents to the API.  These document could be exposed over Atom feeds if there are 3rd parties wishing to process them as well.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-api#9
