### ISSUE TITLE
API Security

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#43]
WHO: Mark

Need to secure api with ssl certificate.

**Comment by momipsl** [comment]
IPSL has obtained a server certificate but it's use would entail moving API to an IPSL server - not sure if we really want to do this at this time.

**Comment by momipsl** [comment]
Need to secure at HTTPS level and also enforce authentication

**Comment by SebastienDenvil** [comment]
How to enforce authentication by the end of May? We need a strategy document about that. For py-esdoc client first, then we will extent. If the CIM questionnaire wrap the pyesdoc-client then we win twice.

**Comment by momipsl** [comment]
This scenario is very different form the CIM Questionnaire.  The focus here is securing the ES-DOC API publishing endpoints.  I would suggest simple HTTPS digest authentication with a simple authenticator at the API which simply performs a whitelist check against a config file.

In the scenario when institute X wishes to leverage pyesdoc to publish documents then the admin workflow is as follows:
  1.  Institute X contacts ES-DOC support to request authentication.
  2.  ES-DOC support generate username / password which is added to authentication whitelist config file.
  3.  ES-DOC supports sends credentials to institute X in an offline manner (a telephone call will suffice).   
  4.  Institute X updates local pyesdoc.json config file which is their responsibility to secure.

The above is very simple and will take a day or so to implement on the API side.

**Comment by SebastienDenvil** [comment]
Let's have a document describing this. Let's circulate this (es-doc-pi + wip). And then if we all agree and we know who will support that charge (es-doc support) then let's implement.

**Comment by murphysj** [comment]
Moving out of any milestone until this is better understood.

**Comment by murphysj** [comment]
Considered top priority in the Feb 2015 F2F

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-api#8
