### ISSUE TITLE
Be able to export CSV directly 

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#44]
WHO: Joe (NCPP)

Currently, to actually download the CSV in the Comparator, you have to:
	1.	Press the CSV button;
	2.	Press CTL-C to copy CSV to clipboard.
	3.	Create a an empty CSV file on their file system.
	4.	Paste CSV from clipboard into file and save.
	5.	Open file in excel.

It would be much better to export this directly.

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-web#20
