### ISSUE TITLE
Phase 2: Enable pyesdoc to validate CIM documents (reg-ex, date ranges, number ranges)

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#54]
WHO: UK Met Office

continue the work of ticket #47.  Enable pyesdoc to validate reg-ex, date ranges, and number ranges.

**Comment by momipsl** [comment]
Implemented

**Comment by murphysj** [comment]
We listed this in the announcement for 0.9.1, so I am moving to that milestone.
