### ISSUE TITLE
Phase 3: Enable pyesdoc to validate CIM documents (cv-terms)

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#55]
WHO: UK Met Office

Completes ticket #47, which enables pyesdoc to validate CIM documents. This ticket covers CV terms (cv-terms).

**Comment by SebastienDenvil** [comment]
What will the source of those cv-terms? How those cv-terms will be versionned?

**Comment by momipsl** [comment]
The ultimate source of these terms are the mind-maps.  However I do not parse the mind-maps themselves, rather I parse a dump of facets emitted by the comparator which is based upon a scan of published documents.

The versioning of the terms is open to discussion but I plan to leverage the emerging pyescv library and GitHub - in essence porting the strategy used in the ipsl-prodiguer platform.

**Comment by SebastienDenvil** [comment]
Let's wait until the whole picture has been depicted.

Le 25/03/2015 15:15, Mark A. Greenslade a écrit :
>
> The ultimate source of these terms are the mind-maps. However I do not 
> parse the mind-maps themselves, rather I parse a dump of facets 
> emitted by the comparator which is based upon a scan of published 
> documents.
>
> The versioning of the terms is open to discussion but I plan to 
> leverage the emerging pyescv library and GitHub - in essence porting 
> the strategy used in the ipsl-prodiguer platform.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/55#issuecomment-86045838>.
>


-- 
Sébastien Denvil
IPSL, Pôle de modélisation du climat
UPMC, Case 101, 4 place Jussieu,
75252 Paris Cedex 5

Tour 45-55 2ème étage Bureau 209
Tel: 33 1 44 27 21 10
Fax: 33 1 44 27 39 02

**Comment by murphysj** [comment]
moving out of any milestone

**Comment by murphysj** [comment]
Considered top priority at the Feb 2015 F2F.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-py-client#7
