### ISSUE TITLE
Enable the Viewer to display when a CIM metadata record was last updated

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#6]
WHO: Tim Schneider (HIWPP)

User want to see when a metadata record was created and or updated. This metadata is already in the CIM and in the metadata records, the Viewer just needs to display it. 

The location should be relatively prominent, either with the other basic information or outside of the tabs someplace.

**Comment by momipsl** [comment]
@allynt Is this metadata being emitted by the new questionniare ?

**Comment by allynt** [comment]
Yes, it is output both as an XML comment and in the ES-DOC specific <meta><createDate> construct.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#18
