### ISSUE TITLE
Display QC status in the Comparator

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#62]
WHO: David Hassell

David is going to be updating CMIP5 metadata. When he does, he will be adding a "peer review status" to the files. This needs to be displayed in the Comparator.

**Comment by murphysj** [comment]
THis has evolved to a series of integers:

0 is unchecked, 1 is checked but not accepted, 2 checking has been accepted

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#22

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-web#29
