### ISSUE TITLE
Ignore components with select QC status in the Comparator 

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#63]
WHO: David Hassell

Once David has put this information into older CMIP5 instances, we need to exclude those from the comparison. 

There will need to be some sort of toggle to show them

Note we also have tickets #61 and #62 to display this information. That is slightly different. 

Since the Viewer pulls up a single instance, there is really no way to exclude them, just display that information so the user knows.

**Comment by momipsl** [comment]
@davidhassell Can you clarify whether this is still a requirement ?

**Comment by davidhassell** [comment]
Hi Mark,

Yes, I think so. Our current thinking is that reviewed=false components/simulations/etc will be not be there in some way (greyed out?), but there should be an option to see them as normal.

All the best,

David

**Comment by murphysj** [comment]
Will need to determine what codes to not to display.

0 is unchecked, 1 is checked but not accepted, 2 checking has been accepted

More may be coming.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#13

**Comment by allynt** [comment]
This issue was moved to ES-DOC/esdoc-web#31
