### ISSUE TITLE
Enable the Comparator to handle scientific property contraints

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#64]
WHO: David Hassell

David found the following while testing version 0.9.1 of the Comparator:

Some attributes do not show up in the output from the Metafor questionnaire NOT because they were not filled in by the modeling groups, but because they were constrained. This constraint shows up easily in the XML.

Does this constraint make it through to the esdoc-mp? 

The Comparator currently puts ??? in place of the attribute, which would indicate the modeling groups did not fill in the information. This is incorrect. 

We will need the Comparator to recognize this constraint and put in a different code. Perhaps "ccc" with the label "NA constraint not met"

**Comment by momipsl** [comment]
It is not possible to implement this as such conditional constraints were improperly encoded in the questionnaire output.
