### ISSUE TITLE
Remove usage of PURL's

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#78]
Until now using the PURL service has been useful as both the ES-DOC domain and deployment environment were moving targets.  Now that they have stabilised the usage of the PURL service can be deprecated.  

All customers using existing PURL's will need to be informed of the pending change so as to give them tie to update their systems accordingly.

**Comment by SebastienDenvil** [comment]
Could you elaborate on this? For example ESGF is a client, COG is a client and the ENES portal is a client. We have to synchronize deployment with them. And we have to somehow have a common roadmap. 
Otherwise features will break at some site.

Is that the timing you have in mind? If clients don't update they will fail to deliver or they will still deliver?
1. es-doc remove PURL
2. client evolves

**Comment by momipsl** [comment]
Yes we need to synchronize - each client simply needs to update the URL it uses to pull in the javascript plugin form the PURL to the static files hosted at http://static.es-doc.org.  I understand that Luca has already updated but not sure about ENES portal.  Once all clients have switched then we can deprecate the PURLs.

However we will still need to retain a few PURL's related to the CIM XML schema which reference them,

**Comment by SebastienDenvil** [comment]
Le 25/03/2015 15:24, Mark A. Greenslade a écrit :
>
> Yes we need to synchronize - each client simply needs to update the 
> URL it uses to pull in the javascript plugin form the PURL to the 
> static files hosted at http://static.es-doc.org. I understand that 
> Luca has already updated but not sure about ENES portal. Once all 
> clients have switched then we can deprecate the PURLs.
>
> However we will still need to retain a few PURL's related to the CIM 
> XML schema which reference them,
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/78#issuecomment-86048525>.
>

Each client will have to properly redeploy a new release. I won't grant 
hotfixes by hand on production system. So let's be sure we have this on 
the roadmap of ESGF current front end, CoG, and the ENES portal.

-- 
Sébastien Denvil
IPSL, Pôle de modélisation du climat
UPMC, Case 101, 4 place Jussieu,
75252 Paris Cedex 5

Tour 45-55 2ème étage Bureau 209
Tel: 33 1 44 27 21 10
Fax: 33 1 44 27 39 02

**Comment by allynt** [comment]
If PURLs are no longer required, then the namespaces for the CIM XML Schemas need to be changed accordingly.  

The new ES-DOC XML (as opposed to the old CMIP5 XML) does not use namespaces.  

The format for a CIM Schema that is used by the Questionnaire does not use namespaces.

The CIM XSD Schemas themselves (that are generated from the UML) still use PURL namespaces.  Not much happens with them anymore.  Is it worth addressing that, or should they just be phased out?

**Comment by momipsl** [comment]
Either we update the namespaces or we maintain the PURLs, or both.  The schemas exist already on GitHub so that could be the canonical location.  Alternatively I could copy them to the ES-DOC static file server (http://static.es-doc.org).  I suspect that the latter is the way to go as because as much as I love GitHub we should not dump on them the responsibility for being the canonical location of these schemas.  

Therefore I could update the deployment process to copy across the schemas to something like http://static.es-doc.org/ontologies/cim/v1.   I could also copy across the UML while we are at it.  We could then update the PURLs and schemas to point to the new location - then after say 3months we could deprecate the PURL's entirely.

**Comment by allynt** [comment]
@momipsl: That sounds like a good plan.  Let me know once you have copied the schemas to the static file server.  Then I will update the namespaces used by the schemas.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#12
