### ISSUE TITLE
Replace JQuery UI with Bootstrap

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#80]
The JQuery UI  plugin has been leveraged by the javascript plugin as well as the search and viewer pages.  This plugin needs to be replaced with the Twitter Bootstrap plugin so as to provide a consistent look and feel across all ES-DOC web UI's.  There is also the advantage that the Twitter Bootstrap plugin is much more modern and better supported.

**Comment by SebastienDenvil** [comment]
Apart look & feel what will be the added value of this change? How much re-engineering is that? It seems not negligible.

**Comment by momipsl** [comment]
The use of this plugin has already almost been deprecated, only the comparator uses it for displaying the progress dialog when it is downloading the setup data on page load.  Therefore the engineering effort is  almost complete.  

The added value other than consistent look and feel is that the javascript plugin download size will be dramatically reduced in size from 450 kb to approx 50 kb.

**Comment by SebastienDenvil** [comment]
Le 25/03/2015 15:30, Mark A. Greenslade a écrit :
>
> The use of this plugin has already almost been deprecated, only the 
> comparator uses it for displaying the progress dialog when it is 
> downloading the setup data on page load. Therefore the engineering 
> effort is almost complete.
>
> The added value other than consistent look and feel is that the 
> javascript plugin download size will be dramatically reduced in size 
> from 450 kb to approx 50 kb.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/80#issuecomment-86050920>.
>
ok. seems to be an easy win.

-- 
Sébastien Denvil
IPSL, Pôle de modélisation du climat
UPMC, Case 101, 4 place Jussieu,
75252 Paris Cedex 5

Tour 45-55 2ème étage Bureau 209
Tel: 33 1 44 27 21 10
Fax: 33 1 44 27 39 02

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#11
