### ISSUE TITLE
Be able to display dictionary information (when it exists) in the tools

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#85]
WHO: Cecelia

Dependent upon a dictionary being created for the CIM

**Comment by momipsl** [comment]
Can you please elaborate upon this ?

**Comment by murphysj** [comment]
Some of the CIM properties have definitions associated with them. Many have
typos and are mall formed. That is one thing that Allyn has been fixing.
This info would need to come in via pyesdoc and not CIM documents.

@allynt, can you provide Mark with an example in the CIM where these exist.

On Tue, Mar 24, 2015 at 7:50 AM, Mark A. Greenslade <
notifications@github.com> wrote:

> Can you please elaborate upon this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-docs/issues/85#issuecomment-85503138>.
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
These definitions appear in the schema, the CVs, and in the CIM Questionnaire webforms.  But they do not appear in CIM output documents.

**Comment by allynt** [comment]
Let me clarify my previous comment:  Every standard or scientific property can potentiall have a definition associated with it.  For example, in the CIM Schema, the "shortName" standard property has the definition "The name of the model (that is used internally)."  This appears as help text in the Questionnaire.  It does not appear in the output XML file that is sent to the ATOM feed.  

However, there is a place in scientific properties to add additional descriptive text to the output.  This is not yet implemented in the Questionnaire, but the hooks are there and it's not very hard to complete.  

I assume this ticket refers to the former, but I'd like to double-check.

**Comment by murphysj** [comment]
There are also definitions in the mindmaps associated with scientific properties. This needs to be displayed too (per David and Eric).

**Comment by murphysj** [comment]
pyescv is going to start controlling the CVs. These definitions should be ingested into this library and made available to the follow on tools

**Comment by bnlawrence** [comment]
I'm not sure what the actual action is here. The information model has what is needed. This is a feature request for tools right? I'm going to remove the CMIP6 label, and replace it with a CMIP6 milestone.

**Comment by momipsl** [comment]
All this type meta-information (i.e. doc strings) is of course part of the ontology definitions within esdoc-mp.  The esdoc-mp code generator copies them across to pyesdoc.  However they are not directly embedded with document instances as that would bloat the size of documents over the wire / on the file system.  Rather the doc strings are available as a map of type --> doc_string or type.property --> doc_string.  The map is available to pyesdoc and as a JSON file.

**Comment by davidhassell** [comment]
Implemented in Questionnaire. Done
