### ISSUE TITLE
Modify the Comparator to handle CIM 1.10

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#92]
WHO: ESPS

ESPS made changes to the CIM (CIM 1.10). They will need to have these new properties:

1) ingestable
2) viewable in the Viewer
3) comparable in the Comparator

**Comment by momipsl** [comment]
Have added extra model component properties to viewer rendering engine.  However they still need to be added to comparator indexation engine.

**Comment by momipsl** [comment]
This issue was moved to ES-DOC/esdoc-web#7
