### ISSUE TITLE
Capitalize project in the Viewer

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-docs#93]
WHO: ESPS 

Currently, the the project in the Viewer is rendering lower case. Most of these are acronyms and should be rendered uppercase. 

The general solution might be to render them as they come in the XML. Not sure if that is upper or lower case for cmip5, dcmip, and esps, all of which should be upper case.

**Comment by momipsl** [comment]
Implemented in 0.9.2 release.

**Comment by murphysj** [comment]
verified on the test server. closing.
