### ISSUE TITLE
Remove duplicate ocean and OGCBio "key" properties from the Comparator

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#96]
The "key" properties related to Ocean and Ocean Bio Chemistry components are being duplicated.

**Comment by momipsl** [comment]
Fixed awaiting deployment.

**Comment by SebastienDenvil** [comment]
When we have a wip-awaiting-testing label where should we go to test?
Do you want me to send that information to the wip. I don't think they know they have to test something.

**Comment by momipsl** [comment]
This label is for internal purposes.  Either Sylvia, Allyn or Ryan will perform testing once this flag has been assigned.  Sylvia tests web tools (i.e. viewer, search, comparator, splash) and either Allyn or Ryan tests command line / python tools.

**Comment by SebastienDenvil** [comment]
Le 25/03/2015 15:18, Mark A. Greenslade a écrit :
>
> This label is for internal purposes. Either Sylvia, Allyn or Ryan will 
> perform testing once this flag has been assigned. Sylvia tests web 
> tools (i.e. viewer, search, comparator, splash) and either Allyn or 
> Ryan tests command line / python tools.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ES-DOC/esdoc-docs/issues/96#issuecomment-86046910>.
>
what is the URL for testing?

-- 
Sébastien Denvil
IPSL, Pôle de modélisation du climat
UPMC, Case 101, 4 place Jussieu,
75252 Paris Cedex 5

Tour 45-55 2ème étage Bureau 209
Tel: 33 1 44 27 21 10
Fax: 33 1 44 27 39 02

**Comment by momipsl** [comment]
All ES-DOC web tools are deployed to test.XXX.es-doc.org for testing, where XXX = splash | search | view | compare | static.

**Comment by murphysj** [comment]
verified by comparing the production server and the test server. The key properties, which were showing up as a separate group of properties under scientific properties, are no longer there. 
closing.
