### ISSUE TITLE
CIM v2.0 support

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-docs#98]
The eco system needs to be extended to support CIM v2.

**Comment by murphysj** [comment]
Since we don't know yet what CIM 2.0 is, should this be moved out of 0.9.2?

**Comment by murphysj** [comment]
@momipsl 

What is the status of this ticket. Should it be closed as part of 0.9.2 or moved out?

**Comment by momipsl** [comment]
Initial support has been added.  CIM 2.0 classes are being generated from CIM 2.0 meta definitions using the ES-DOC meta-programming framework.  All that remains is to extend the HTML generation support - so this ticket can be closed.
